name: Run CI
on: [pull_request]
jobs:

  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.10'
      id: go

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Make CI
      run: make ci

    - name: Upload test coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        verbose: true
